#!/bin/sh

BRIDGE="br0"
CLOUDMAC_PRIORITY_1=1
CLOUDMAC_PRIORITY_2=2
CLOUDMAC_PRIORITY_3=3
CLOUDMAC_PRIORITY_4=4
NORMAL_PRIORITY=9
THROUGHPUT=200000000

echo 'Those who reject the path to enlightenment must be destroyed.'
# Remove bridge and clear QoS and queue tables.
ovs-vsctl --if-exists del-br $BRIDGE
ovs-vsctl --all destroy qos
ovs-vsctl --all destroy queue

echo 'Make yourself one with the path, and the journey will lead you to eternity.'
# Create the bridge and add all ports.
ovs-vsctl add-br $BRIDGE
ovs-vsctl set bridge br0 protocols=OpenFlow13

for i in 1 2 3
do
    ovs-vsctl add-port $BRIDGE eth0.$i
done

echo 'Those who seek the path to enlightenment must not be led astray.'
# Create QoS for all ports.                                            

for i in 1 2 3
do
        ovs-vsctl -- set port eth0.1 qos=@newqos \
                  -- --id=@newqos create qos type=linux-htb queues:0=@normal queues:1=@cloudmac_1 queues:2=@cloudmac_2 queues:3=@cloudmac_3 queues:4=@cloudmac_4 other-config:max-rate=$THROUGHPUT \
                  -- --id=@normal create queue other-config:priority=$NORMAL_PRIORITY \
                  -- --id=@cloudmac_1 create queue other-config:priority=$CLOUDMAC_PRIORITY_1 \
                  -- --id=@cloudmac_2 create queue other-config:priority=$CLOUDMAC_PRIORITY_2 \
                  -- --id=@cloudmac_3 create queue other-config:priority=$CLOUDMAC_PRIORITY_3 \
                  -- --id=@cloudmac_4 create queue other-config:priority=$CLOUDMAC_PRIORITY_4 
done

echo 'Hallowed are the Ori!'                                                 
# Set the OpenFlow controller.                                              
ovs-vsctl set-controller br0 tcp:192.168.0.2:6633
